/**
 * Hemelval reference dataset — curated SA wines and estates for offline/demo mode.
 *
 * This is DEMO FALLBACK data used only when the live Supabase DB is unreachable.
 * The live DB (420 estates, 217 wines) is the primary data source via dataAccessor.ts.
 *
 * DATA QUALITY NOTE:
 * The 41 wines and 30 estates below are REAL South African producers with verified
 * names, regions, and histories. However, the numeric fields — avgStars, ratingCount,
 * priceZar, abv — are EDITORIAL ESTIMATES for demo purposes, not sourced from
 * Platter's, Tim Atkin, or Vivino. They should not be presented as verified ratings.
 * When the live DB returns wines with avg_stars = NULL, the UI shows "Not yet rated"
 * rather than fabricating a score.
 *
 * The awards arrays are compiled from publicly reported results but have not been
 * individually verified against the awarding body's official records.
 */

import { VARIETALS, suggestPairings, servingTempFor } from '@kelder/engine';

export interface MockEstate {
  id: string; slug: string; name: string; region: string; wineRoute: string;
  founded?: number; about: string; famousFor: string; verified: boolean;
  certifications: string[]; lat: number; lng: number; website: string;
  history?: string; awards?: MockAward[]; wineRouteUrl?: string;
  tastingRoom?: string; sustainabilityNote?: string;
}

export interface MockAward {
  body: string; result: string; year: number; wine?: string;
}

/** Human-readable certification metadata (code → {name, description, category}). */
export const CERT_INFO: Record<string, { name: string; description: string; category: 'origin' | 'sustainability' | 'ethics' | 'heritage' }> = {
  WO: { name: 'Wine of Origin', description: 'Guarantees certified origin (appellation), vintage year, and cultivar. Administered by the Wine & Spirit Board.', category: 'origin' },
  IPW: { name: 'Integrated Production of Wine', description: 'Voluntary environmental sustainability scheme — audited vineyard & cellar practices since 1998.', category: 'sustainability' },
  WIETA: { name: 'WIETA Ethical Trade', description: "SA ethical-trade standard — fair labour, human rights, dignified working conditions.", category: 'ethics' },
  BWI: { name: 'Biodiversity & Wine Initiative', description: 'Partners estates with conservation of the Cape Floral Kingdom. "Champion" status for top performers.', category: 'sustainability' },
  OVP: { name: 'Old Vine Project (Heritage Vineyards)', description: 'World-first seal authenticating wines from vines 35+ years old; displays the planting year on the bottle.', category: 'heritage' },
  ROC: { name: 'Regenerative Organic Certified', description: 'Newer regenerative standard — soil health, animal welfare, social fairness.', category: 'sustainability' },
  FAIRTRADE: { name: 'Fairtrade', description: 'International ethical premium — community development premium per bottle.', category: 'ethics' },
};

export interface MockWine {
  id: string; slug: string; name: string; estateId: string; estateName: string;
  type: 'red' | 'white' | 'rose' | 'sparkling' | 'fortified' | 'dessert' | 'orange';
  varietals: string[]; region: string; avgStars: number; ratingCount: number;
  priceZar?: number; abv?: number; year: number; about: string; pairings: string[];
  serving: string; barcode?: string;
}

export const MOCK_ESTATES: MockEstate[] = [
  { id: 'e1', slug: 'kanonkop', name: 'Kanonkop', region: 'Simonsberg-Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', wineRouteUrl: 'https://wineroute.co.za/', founded: 1680, about: 'The "undisputed benchmark" for Pinotage. Famed for the Paul Sauer Bordeaux blend.', famousFor: 'Pinotage (benchmark); Paul Sauer Bordeaux blend', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.8925, lng: 18.8833, website: 'https://www.kanonkop.co.za/',
    history: 'Kanonkop ("cannon hill") takes its name from the historical signal cannon fired to warn of approaching ships. The farm has been in the Sauer family for generations and pioneered serious Pinotage as a noble grape — transforming what was once a workhorse crossing into one of SA\'s most collectible reds. Fourth-generation brothers Johan and Paul Sauer (with winemaker Abrie Beeslaar) continue the legacy.',
    awards: [
      { body: 'Tim Atkin MW', result: '95/100', year: 2023, wine: 'Pinotage' },
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Paul Sauer' },
      { body: 'Veritas', result: 'Double Gold', year: 2023, wine: 'Cabernet Sauvignon' },
      { body: 'IWSC', result: 'Gold', year: 2022, wine: 'Pinotage' },
    ],
    tastingRoom: 'Tastings by appointment · Mon–Fri 10:00–16:00',
    sustainabilityNote: 'IPW-certified; WIETA ethical-trade compliant. Dryland bush vines on the lower slopes.',
  },
  { id: 'e2', slug: 'klein-constantia', name: 'Klein Constantia', region: 'Constantia', wineRoute: 'Constantia Wine Route', wineRouteUrl: 'https://constantiawineroute.com/', founded: 1685, about: 'Birthplace of the legendary Vin de Constance — the natural sweet wine loved by European royalty.', famousFor: 'Vin de Constance; Sauvignon Blanc', verified: true, certifications: ['WO', 'IPW', 'WIETA', 'BWI'], lat: -34.0205, lng: 18.4395, website: 'https://www.kleinconstantia.com/',
    history: 'Part of the original 1685 Constantia estate established by Governor Simon van der Stel — making it one of the oldest wine farms in the Southern Hemisphere. Vin de Constance, the natural sweet Muscat wine, was celebrated across 18th- and 19th-century Europe: Napoleon requested it on his deathbed, Dickens and Jane Austen wrote of it. The estate was revived in the 1980s and Vin de Constance painstakingly recreated.',
    awards: [
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Vin de Constance' },
      { body: 'Tim Atkin MW', result: '97/100', year: 2023, wine: 'Vin de Constance' },
      { body: 'Decanter DWWA', result: 'Platinum', year: 2022, wine: 'Vin de Constance' },
    ],
    tastingRoom: 'Open daily · 10:00–17:00 · booking recommended',
    sustainabilityNote: 'BWI Champion — conserves Cape Floral Kingdom on the steep sea-facing slopes. IPW + WIETA.',
  },
  { id: 'e3', slug: 'sadie-family', name: 'Sadie Family Wines', region: 'Paardeberg (Swartland)', wineRoute: 'Swartland Wine & Olive Route', wineRouteUrl: 'https://swartlandwineandolives.co.za/', founded: 1999, about: 'Eben Sadie. Columella (top SA Rhône red), Skurfberg old-vine Chenin. SA\'s first ROC vineyard.', famousFor: 'Columella; Skurfberg Chenin; old-vine Chenin', verified: true, certifications: ['WO', 'OVP', 'ROC'], lat: -33.3167, lng: 18.7333, website: 'https://www.sadiefamilywines.com/',
    history: 'Eben Sadie, a former sommelier turned winemaker, is widely regarded as the pioneer of the modern Swartland revolution. He sources from ancient dryland bush vines — some over 60 years old — across the Paardeberg and Citrusdal Mountain. Columella (2000 vintage, first release) became the first South African wine to be compared to the great Rhône reds. Sadie Family Wines is SA\'s first Regenerative Organic Certified (ROC) vineyard, a global standard for soil health and social fairness.',
    awards: [
      { body: 'Tim Atkin MW', result: '98/100', year: 2023, wine: 'Columella' },
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Skurfberg Chenin' },
      { body: 'James Suckling', result: '99/100', year: 2023, wine: 'Columella' },
    ],
    tastingRoom: 'By appointment only · intimate cellar tastings',
    sustainabilityNote: 'SA\'s first Regenerative Organic Certified (ROC) vineyard. Old Vine Project heritage vines (35+ yrs).',
  },
  { id: 'e4', slug: 'hamilton-russell', name: 'Hamilton Russell Vineyards', region: 'Hemel-en-Aarde Valley', wineRoute: 'Hemel-en-Aarde', wineRouteUrl: 'https://www.hemelenaardewines.com/', founded: 1975, about: 'Founder of Hemel-en-Aarde (1975). Pinot Noir & Chardonnay benchmark; most southerly, maritime.', famousFor: 'Pinot Noir; Chardonnay', verified: true, certifications: ['WO', 'IPW'], lat: -34.4167, lng: 19.2, website: 'https://hamiltonrussellvineyards.com/',
    history: 'Tim Hamilton Russell founded the estate in 1975, believing the cool, maritime, most-southerly tip of Africa could produce world-class Pinot Noir and Chardonnay — a radical bet at the time. He proved correct; his son Anthony (third generation) now runs the estate, which remains single-mindedly devoted to just those two varieties. Hamilton Russell effectively put the Hemel-en-Aarde Valley on the global fine-wine map.',
    awards: [
      { body: 'Tim Atkin MW', result: '96/100', year: 2023, wine: 'Pinot Noir' },
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Chardonnay' },
    ],
    tastingRoom: 'Open Mon–Sat · 10:00–16:00',
    sustainabilityNote: 'IPW-certified. Maritime, low-intervention; the cool climate does the work.',
  },
  { id: 'e5', slug: 'boekenhoutskloof', name: 'Boekenhoutskloof', region: 'Franschhoek', wineRoute: 'Franschhoek Wine Valley', wineRouteUrl: 'https://franschhoek.org.za/', founded: 1776, about: 'The Chocolate Block, Syrah, single-vineyard Semillon — one of SA\'s most successful modern brands.', famousFor: 'The Chocolate Block; Syrah; Semillon', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.9167, lng: 19.1167, website: 'https://www.boekenhoutskloof.co.za/',
    history: 'Founded in 1776, the farm was revitalised in 1993 by a group of passionate winemakers led by Marc Kent. "Boekenhoutskloof" refers to the indigenous boekenhout (cape beech) that once covered the valley. The Chocolate Block — a Rhône-style blend — became one of SA\'s most commercially successful modern wines, opening the door for premium SA blends internationally.',
    awards: [
      { body: 'Platter\'s', result: '5★', year: 2023, wine: 'Semillon' },
      { body: 'Tim Atkin MW', result: '96/100', year: 2024, wine: 'Syrah' },
      { body: 'Decanter DWWA', result: 'Gold', year: 2023, wine: 'The Chocolate Block' },
    ],
    tastingRoom: 'Tastings by appointment',
    sustainabilityNote: 'IPW + WIETA. Sources fruit from certified sustainable Swartland and Franschhoek growers.',
  },
  { id: 'e6', slug: 'graham-beck', name: 'Graham Beck', region: 'Robertson', wineRoute: 'Robertson Wine Valley', wineRouteUrl: 'https://robertsonwinevalley.com/', founded: 1983, about: 'Iconic MCC producer. Brut, Rosé — the SA Cap Classique benchmark.', famousFor: 'MCC Brut; MCC Rosé', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.8, lng: 19.8833, website: 'https://grahambeck.com/',
    history: 'Founded by the late entrepreneur Graham Beck (also once owner of a stakes in the SA wine + game industries), the estate set out to make world-class Méthode Cap Classique using traditional Champagne methods on the limestone-rich Robertson soils. The Brut was famously served at both Nelson Mandela\'s 1994 inauguration and Barack Obama\'s 2008 election night. Cellar-master Pieter "Bubbles" Ferreira has led winemaking for over 30 years.',
    awards: [
      { body: 'Tim Atkin MW', result: '95/100', year: 2024, wine: 'Brut MCC' },
      { body: 'Platter\'s', result: '5★', year: 2023, wine: 'Cuvée Clive' },
      { body: 'Michelangelo', result: 'Gold', year: 2023, wine: 'Rosé MCC' },
    ],
    tastingRoom: 'Open daily · 09:00–17:00 · cellar tours by booking',
    sustainabilityNote: 'IPW + WIETA. Biodiversity reserve on the property; carbon-reduction programme.',
  },
  { id: 'e7', slug: 'ken-forrester', name: 'Ken Forrester', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', wineRouteUrl: 'https://wineroute.co.za/', founded: 1689, about: '"Mr Chenin Blanc". The FMC, Old Vines Reserve — benchmark SA Chenin.', famousFor: 'Chenin Blanc (The FMC); Old Vines Reserve', verified: true, certifications: ['WO', 'IPW', 'WIETA', 'OVP'], lat: -33.9333, lng: 18.8333, website: 'https://www.kenforresterwines.com/',
    history: 'Ken Forrester, a former restaurateur, purchased the historic 1689 farm (then called Zandberg) in 1993 and made it his mission to champion Chenin Blanc — SA\'s most planted grape but long undervalued. His flagship The FMC (Forrester Meinert Chenin, a partnership with winemaker Martin Meinert) helped redefine what serious SA Chenin could be. He is widely called "Mr Chenin Blanc".',
    awards: [
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'The FMC' },
      { body: 'Tim Atkin MW', result: '95/100', year: 2023, wine: 'The FMC' },
    ],
    tastingRoom: 'Open daily · restaurant on site (96 Winery Road)',
    sustainabilityNote: 'IPW + WIETA + Old Vine Project heritage vines (35+ yrs).',
  },
  { id: 'e8', slug: 'mullineux', name: 'Mullineux', region: 'Swartland', wineRoute: 'Swartland Wine & Olive Route', wineRouteUrl: 'https://swartlandwineandolives.co.za/', founded: 2007, about: 'Chris & Andrea Mullineux. Syrah, old-vine Chenin, Straw Wine. Part of Leeu Family Wines.', famousFor: 'Syrah; old-vine Chenin; Straw Wine', verified: true, certifications: ['WO', 'OVP'], lat: -33.3167, lng: 18.7333, website: 'https://mullineuxwines.com/',
    history: 'Andrea Mullineux (a Californian who trained in Stellenbosch) and her husband Chris were central figures in the Swartland revolution alongside Eben Sadie. They source from old dryland bush vines, vinifying each parcel separately. The Mullineux Syrah and old-vine Chenin are now benchmarks; the Straw Wine (air-dried Chenin) is a modern SA classic. Now part of the Leeu Family Wines portfolio with the Leeu Passant label.',
    awards: [
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Syrah' },
      { body: 'Tim Atkin MW', result: '97/100', year: 2023, wine: 'Old Vines Chenin' },
      { body: 'Decanter DWWA', result: 'Gold', year: 2022, wine: 'Straw Wine' },
    ],
    tastingRoom: 'Tastings at Leeu Estate by appointment',
    sustainabilityNote: 'Old Vine Project heritage vines. Dryland, low-intervention viticulture.',
  },
  { id: 'e9', slug: 'vergelegen', name: 'Vergelegen', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', wineRouteUrl: 'https://wineroute.co.za/', founded: 1700, about: 'Often ranked SA\'s #1 iconic farm. Cabernet, Sauvignon Blanc, GVB Red.', famousFor: 'Cabernet Sauvignon; GVB Red', verified: true, certifications: ['WO', 'IPW', 'WIETA', 'BWI'], lat: -34.0833, lng: 18.9167, website: 'https://www.vergelegen.co.za/',
    history: 'Founded in 1700 by Governor Willem Adriaan van der Stel, Vergelegen ("situated far away") became a showpiece Cape farm with remarkable camphor trees (now national monuments), a historic homestead, and one of the oldest libraries in SA. The estate passed through several owners before being bought by Anglo American in 1987, who restored it to world-class status. Today often ranked as SA\'s #1 iconic farm.',
    awards: [
      { body: 'Tim Atkin MW', result: '96/100', year: 2024, wine: 'GVB Red' },
      { body: 'Platter\'s', result: '5★', year: 2023, wine: 'Cabernet Sauvignon' },
      { body: 'Veritas', result: 'Double Gold', year: 2023, wine: 'GVB Red' },
    ],
    tastingRoom: 'Open daily · 09:30–16:00 · heritage tours available',
    sustainabilityNote: 'BWI Champion (1900ha conservation area). IPW + WIETA. One of SA\'s largest private reforestation programmes.',
  },
  { id: 'e10', slug: 'iona', name: 'Iona', region: 'Elgin', wineRoute: 'Elgin Wine Route', wineRouteUrl: 'https://www.winesofelgin.co.za/', founded: 1997, about: 'Cool-climate benchmark. Sauvignon Blanc, Chardonnay, Pinot Noir.', famousFor: 'Sauvignon Blanc; Chardonnay; Pinot Noir', verified: true, certifications: ['WO', 'IPW'], lat: -34.1667, lng: 19.0, website: 'https://www.iona.co.za/',
    history: 'Andrew Gunn bought the remote 420ha Elgin property in 1997, betting that its altitude (420m), ocean views and cold Kogelberg-biosphere climate could produce SA\'s finest cool-climate whites. The gamble paid off: Iona Sauvignon Blanc and Chardonnay are now among the most elegant in the country, defined by natural acidity and restraint. One of the pioneering estates that put Elgin on the fine-wine map.',
    awards: [
      { body: 'Platter\'s', result: '5★', year: 2024, wine: 'Sauvignon Blanc' },
      { body: 'Tim Atkin MW', result: '94/100', year: 2023, wine: 'Chardonnay' },
    ],
    tastingRoom: 'By appointment',
    sustainabilityNote: 'IPW-certified. Located within the Kogelberg Biosphere Reserve — high-altitude, cool-climate viticulture.',
  },
  // ── 20 NEW ESTATES (e11–e30) ──────────────────────────────────────────────
  { id: 'e11', slug: 'meerlust', name: 'Meerlust', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1693, about: 'Historic estate (Myburgh family since 1756). Home of Rubicon, the iconic SA Bordeaux blend.', famousFor: 'Rubicon Bordeaux blend; Cabernet Sauvignon', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -34.0086, lng: 18.8306, website: 'https://www.meerlust.co.za/',
    history: 'Meerlust has been owned by the Myburgh family since 1756 — one of SA\'s oldest continuously family-owned estates. The Cape Dutch manor dates to 1756. Hanni Myburgh continues the legacy, with the Rubicon Bordeaux blend (first made in 1980) becoming one of SA\'s most iconic and collectible reds.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2023, wine: 'Rubicon' }, { body: 'Tim Atkin MW', result: '95/100', year: 2024, wine: 'Rubicon' }],
    tastingRoom: 'By appointment · Mon–Fri', sustainabilityNote: 'IPW + WIETA. Biodiversity reserve along the Eerste River.',
  },
  { id: 'e12', slug: 'rustenberg', name: 'Rustenberg', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1682, about: 'Historic (1682). Chardonnay, Peter Barlow Cabernet, and the John X Merriman blend.', famousFor: 'Chardonnay; Peter Barlow Cabernet Sauvignon', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.875, lng: 18.8583, website: 'https://www.rustenberg.co.za/',
    history: 'Rustenberg was founded in 1682, making it one of the oldest estates in Stellenbosch. The Barlow family has owned it since 1941 — three generations. The Peter Barlow Cabernet Sauvignon honours the patriarch who restored the farm. The Chardonnay is a perennial SA benchmark.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2023, wine: 'Peter Barlow Cabernet' }],
    tastingRoom: 'Open daily · 10:00–16:00', sustainabilityNote: 'IPW + WIETA. Mountain fynbos conservation.',
  },
  { id: 'e13', slug: 'thelema', name: 'Thelema Mountain Vineyards', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1983, about: 'Helshoogte Pass estate. Bordeaux reds and Sauvignon Blanc.', famousFor: 'Bordeaux reds; Sauvignon Blanc', verified: true, certifications: ['WO', 'IPW'], lat: -33.9333, lng: 18.9167, website: 'https://www.thelema.co.za/',
    history: 'Thelema was established in 1983 by Gyles Webb on the Helshoogte Pass — one of the first modern "boutique" estates in Stellenbosch. Its Bordeaux-style reds and crisp Sauvignon Blanc set a template for the quality revolution of the 1990s.',
    awards: [{ body: 'Tim Atkin MW', result: '93/100', year: 2023, wine: 'Merlot' }],
    tastingRoom: 'Open Mon–Sat · 10:00–16:00', sustainabilityNote: 'IPW-certified.',
  },
  { id: 'e14', slug: 'simonsig', name: 'Simonsig', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1688, about: 'MCC pioneer (first SA Cap Classique 1971). Pinotage and Chenin Blanc.', famousFor: 'Cap Classique (pioneer); Pinotage; Chenin Blanc', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.8667, lng: 18.85, website: 'https://www.simonsig.co.za/',
    history: 'The Malan family has farmed Simonsig since 1688. Frans Malan produced South Africa\'s first bottle-fermented sparkling wine (Cap Classique) in 1971 — the Kaapse Vonkel — earning Simonsig the title "the pioneer of MCC". The estate remains family-run (third generation).',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2024, wine: 'Kaapse Vonkel Brut' }],
    tastingRoom: 'Open daily · 09:00–17:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e15', slug: 'boschendal', name: 'Boschendal', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1685, about: 'Iconic 1685 estate. MCC, 1685 range, famous farm-to-table dining.', famousFor: 'MCC; 1685 range; farm dining', verified: true, certifications: ['WO', 'IPW', 'WIETA', 'BWI'], lat: -33.8833, lng: 18.95, website: 'https://www.boschendal.com/',
    history: 'Founded in 1685, Boschendal is one of the oldest wine farms in the Cape. Its Cape Dutch manor house is a national monument. The estate was revitalised in the 2010s with a focus on sustainability, regenerative farming, and one of the Winelands\' best farm-to-table restaurants.',
    awards: [{ body: 'Veritas', result: 'Gold', year: 2023, wine: '1685 Cabernet Sauvignon' }],
    tastingRoom: 'Open daily · 09:00–17:00', sustainabilityNote: 'BWI Champion + IPW + WIETA. Regenerative agriculture programme.',
  },
  { id: 'e16', slug: 'warwick', name: 'Warwick', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1771, about: 'Bordeaux-style blends (Three Cape Ladies), Pinotage.', famousFor: 'Three Cape Ladies blend; Pinotage', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.8833, lng: 18.85, website: 'https://www.warwickwine.com/',
    history: 'Warwick was established in 1771 and named after the Warwickshire regiment. Norma Ratcliffe — SA\'s first female winemaker to gain international acclaim — pioneered the estate\'s Bordeaux-style blends in the 1980s, earning the nickname "The First Lady of SA Wine".',
    awards: [{ body: 'Tim Atkin MW', result: '93/100', year: 2023, wine: 'Three Cape Ladies' }],
    tastingRoom: 'Open daily · 10:00–17:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e17', slug: 'nederburg', name: 'Nederburg', region: 'Paarl', wineRoute: 'Paarl Wine Route', founded: 1937, about: 'Most-awarded global SA brand. Cabernet, Pinotage, II Heroes.', famousFor: 'Cabernet Sauvignon; Pinotage', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.7333, lng: 18.9667, website: 'https://www.nederburg.com/',
    history: 'Founded in 1937 by German immigrant Johann Graue, Nederburg became SA\'s most award-winning winery under winemaker Günter Brözel (1956–1989). The Nederburg Auction was for decades the most important event on the SA wine calendar. Today owned by Heineken/DGB.',
    awards: [{ body: 'IWSC', result: 'Gold', year: 2023, wine: 'II Heroes Cabernet' }, { body: 'Veritas', result: 'Double Gold', year: 2024, wine: 'Heritage Anchorman Chenin' }],
    tastingRoom: 'Open daily · 10:00–17:00', sustainabilityNote: 'IPW + WIETA. Lighter-glass bottles to reduce carbon.',
  },
  { id: 'e18', slug: 'fairview', name: 'Fairview', region: 'Paarl', wineRoute: 'Paarl Wine Route', founded: 1693, about: 'Charles Back\'s estate. Wines + famous artisanal cheese. Pinotage, Shiraz.', famousFor: 'Pinotage; Shiraz; artisanal cheese', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.7667, lng: 18.9333, website: 'https://www.fairview.co.za/',
    history: 'Fairview has been in the Back family since 1937. Charles Back transformed it into one of SA\'s most innovative estates — pioneering Rhône varieties and building the famous goat tower. The Fairview cheesery is SA\'s largest artisanal cheese producer. The estate\'s wine + cheese pairing is a Winelands institution.',
    awards: [{ body: 'Platter\'s', result: '4.5★', year: 2024, wine: 'Jakkalsfontein Syrah' }],
    tastingRoom: 'Open daily · 09:00–17:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e19', slug: 'durbanville-hills', name: 'Durbanville Hills', region: 'Durbanville', wineRoute: 'Durbanville Wine Valley', founded: 1998, about: 'Co-op; top-10 cellar. Sauvignon Blanc from cool maritime hills.', famousFor: 'Sauvignon Blanc; Rhinofields range', verified: true, certifications: ['WO', 'IPW'], lat: -33.85, lng: 18.6333, website: 'https://www.durbanvillehills.co.za/',
    history: 'Founded in 1998 by nine Durbanville farmers pooling their fruit, Durbanville Hills quickly became one of SA\'s top-rated cellars. The cool maritime climate — only 20km from the Atlantic — makes it one of the best Sauvignon Blanc regions in the country.',
    awards: [{ body: 'Veritas', result: 'Gold', year: 2023, wine: 'Rhinofields Sauvignon Blanc' }],
    tastingRoom: 'Open Mon–Sat · 10:00–17:00', sustainabilityNote: 'IPW-certified.',
  },
  { id: 'e20', slug: 'de-grendel', name: 'De Grendel', region: 'Durbanville', wineRoute: 'Durbanville Wine Valley', founded: 1720, about: 'Graaff family estate with sweeping Table Bay views.', famousFor: 'Sauvignon Blanc; Pinotage; Koetshuis', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.85, lng: 18.5833, website: 'https://www.degrendel.co.za/',
    history: 'The Graaff family has owned De Grendel since 1720. Sir David Graaff, former mayor of Cape Town, built the estate into a modern benchmark. The restaurant (Koetshuis) is one of the Winelands\' most scenic dining spots, with views across Table Bay to Table Mountain.',
    awards: [{ body: 'Tim Atkin MW', result: '92/100', year: 2023, wine: 'Sauvignon Blanc' }],
    tastingRoom: 'Open daily · 10:00–17:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e21', slug: 'de-wetshof', name: 'De Wetshof', region: 'Robertson', wineRoute: 'Robertson Wine Valley', founded: 1972, about: 'Danie de Wet. Leading Chardonnay (Site of Origin, Bateleur), limestone-driven.', famousFor: 'Chardonnay (Site of Origin, Bateleur)', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.8, lng: 19.8833, website: 'https://www.dewetshof.co.za/',
    history: 'Danie de Wet founded the estate in 1972 and was the first SA winemaker to register as a estate wine producer in Robertson. He studied in Germany and brought European precision to the limestone-rich Robertson soils. De Wetshof Chardonnay — particularly the Site of Origin and the barrel-fermented Bateleur — is a perennial SA benchmark.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2024, wine: 'Bateleur Chardonnay' }],
    tastingRoom: 'Open Mon–Fri · 09:00–17:00', sustainabilityNote: 'IPW + WIETA. Limestone-rich soils naturally limit disease.',
  },
  { id: 'e22', slug: 'springfield', name: 'Springfield Estate', region: 'Robertson', wineRoute: 'Robertson Wine Valley', founded: 1987, about: 'Sauvignon Blanc (Life from Stone, Wild Yeast), Méthode Ancienne Cabernet.', famousFor: 'Life from Stone Sauvignon; Wild Yeast; Méthode Ancienne', verified: true, certifications: ['WO', 'IPW'], lat: -33.8, lng: 19.8833, website: 'https://www.springfieldestate.com/',
    history: 'Springfield is run by the Bruwer family (brother-and-sister team Abrie and Jeanetta). Their philosophy is minimal intervention: wild yeast fermentation, no fining, no filtering. The Life from Stone Sauvignon Blanc — grown on a stony quartz vineyard — is one of SA\'s most distinctive and sought-after whites.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2023, wine: 'Life from Stone Sauvignon Blanc' }],
    tastingRoom: 'Open Mon–Sat · 10:00–16:00', sustainabilityNote: 'IPW. Wild-yeast, minimal-intervention winemaking.',
  },
  { id: 'e23', slug: 'creation-wines', name: 'Creation Wines', region: 'Hemel-en-Aarde Valley', wineRoute: 'Hemel-en-Aarde', founded: 2002, about: 'Wide cool-climate range; acclaimed food pairings. Pinot Noir, Chardonnay, Syrah.', famousFor: 'Pinot Noir; Chardonnay; Syrah', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -34.4167, lng: 19.2, website: 'https://www.creationwines.com',
    history: 'Creation was founded in 2002 by Jean-Claude (JC) Martin, a Swiss-trained winemaker, and his wife Carolyn. The estate sits on the highest ridge of the Hemel-en-Aarde Valley. Creation is known for its exceptionally wide range (over 30 wines) and its food-and-wine pairing experiences, which draw visitors from across the globe.',
    awards: [{ body: 'Tim Atkin MW', result: '95/100', year: 2024, wine: 'Pinot Noir Reserve' }],
    tastingRoom: 'Open daily · 10:00–17:00 (booking essential)', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e24', slug: 'bouchard-finlayson', name: 'Bouchard Finlayson', region: 'Hemel-en-Aarde Valley', wineRoute: 'Hemel-en-Aarde', founded: 1989, about: 'Pinot Noir, Tinto blend, Galpin Peak. Est. 1989.', famousFor: 'Pinot Noir; Galpin Peak; Tinto', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -34.4167, lng: 19.2, website: 'https://www.bouchardfinlayson.co.za',
    history: 'Founded in 1989 by Paul Bouchard (of the Beaune wine family) and Peter Finlayson, who had trained under Tim Hamilton Russell. Bouchard Finlayson was the second estate to plant Pinot Noir in the Hemel-en-Aarde. The Galpin Peak Pinot Noir — named after the mountain above the vineyard — is one of SA\'s most celebrated.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2023, wine: 'Galpin Peak Pinot Noir' }],
    tastingRoom: 'Open Wed–Sun · 10:00–16:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e25', slug: 'paul-cluver', name: 'Paul Cluver Wines', region: 'Elgin', wineRoute: 'Elgin Wine Route', founded: 1898, about: 'Top-ranked Elgin cellar. Pinot Noir, Riesling, Chardonnay, Gewürztraminer.', famousFor: 'Pinot Noir; Riesling; Chardonnay', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -34.1667, lng: 19.0, website: 'https://www.paulcluver.com/',
    history: 'The Cluver family has farmed in Elgin since 1898 — originally apples, then vines. Paul Cluver Sr planted the first vines in the 1980s, betting (like Iona\'s Andrew Gunn) that Elgin\'s cool high-altitude climate could produce fine wine. He was right. The estate\'s Riesling is one of the very few serious examples in SA, and the Pinot Noir is a perennial Elgin benchmark.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2024, wine: 'Riesling' }],
    tastingRoom: 'Open Mon–Sat · 10:00–16:00', sustainabilityNote: 'IPW + WIETA. Kogelberg Biosphere.',
  },
  { id: 'e26', slug: 'aa-badenhorst', name: 'AA Badenhorst Family Wines', region: 'Swartland', wineRoute: 'Swartland Wine & Olive Route', founded: 2009, about: 'Adi Badenhorst. Kalmoesfontein, Secateurs, old-vine Chenin.', famousFor: 'Secateurs; Kalmoesfontein; old-vine Chenin', verified: true, certifications: ['WO', 'OVP'], lat: -33.3667, lng: 18.8667, website: 'https://www.aabadenhorst.com/',
    history: 'Adi Badenhorst — grandson of the legendary Kanonkop winemaker Jan Badenhorst — left Rustenberg in 2009 to buy Kalmoesfontein, a run-down Paardeberg farm. Together with cousins Hein and Janno, he restored it and became a central figure (with Eben Sadie and the Mullineuxs) of the Swartland revolution. The Secateurs range (red + white) is one of SA\'s best-value natural-leaning wines.',
    awards: [{ body: 'Tim Atkin MW', result: '95/100', year: 2023, wine: 'Kalmoesfontein Red' }],
    tastingRoom: 'By appointment', sustainabilityNote: 'Old Vine Project heritage vines.',
  },
  { id: 'e27', slug: 'spier', name: 'Spier', region: 'Stellenbosch', wineRoute: 'Stellenbosch Wine Routes', founded: 1692, about: 'Historic 1692 farm with broad range and major tourism.', famousFor: 'Wide range; farm-to-table dining; Wine Trader', verified: true, certifications: ['WO', 'IPW', 'WIETA', 'BWI'], lat: -33.9167, lng: 18.85, website: 'https://www.spier.co.za/',
    history: 'Spier is one of the oldest wine farms in South Africa (1692). It was the first SA wine farm to receive WIETA ethical certification. Today Spier is one of the Winelands\' most visited estates, known for its broad range, river-side picnics, eagle-owl encounters, and the hotel.',
    awards: [{ body: 'Veritas', result: 'Gold', year: 2023, wine: 'Creative Block 5' }],
    tastingRoom: 'Open daily · 09:00–17:00', sustainabilityNote: 'BWI Champion + IPW + WIETA.',
  },
  { id: 'e28', slug: 'boplaas', name: 'Boplaas', region: 'Calitzdorp', wineRoute: 'Klein Karoo Wine Route', founded: 1880, about: 'The "port" house of SA. Carel Nel. Tinta Barroca, Touriga Nacional, Cape pot-stilled brandy.', famousFor: 'Cape Tawny; Vintage Reserve; brandy', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.4833, lng: 21.6833, website: 'https://www.boplaas.co.za/',
    history: 'The Nel family has farmed at Boplaas since 1880, making it one of the oldest family wineries in the Klein Karoo. Carel Nel was the first SA producer to plant Portuguese varieties (Tinta Barroca, Touriga Nacional) for port-style wines. Boplaas Cape Vintage Reserve is the benchmark SA port-style wine, and the estate\'s pot-stilled brandy is among SA\'s finest.',
    awards: [{ body: 'Veritas', result: 'Double Gold', year: 2024, wine: 'Cape Vintage Reserve' }],
    tastingRoom: 'Open Mon–Sat · 09:00–17:00', sustainabilityNote: 'IPW + WIETA.',
  },
  { id: 'e29', slug: 'cederberg', name: 'Cederberg Private Cellar', region: 'Cederberg', wineRoute: 'Cederberg Wine Route', founded: 1990, about: 'High-altitude (1000m+) benchmark for the ward. Cabernet Sauvignon, Sauvignon Blanc.', famousFor: 'Cabernet Sauvignon; Sauvignon Blanc; Five Generations', verified: true, certifications: ['WO', 'IPW'], lat: -32.5, lng: 19.0, website: 'https://www.cederbergwine.com/',
    history: 'The Nieuwoudt family has farmed in the Cederberg mountains for five generations. At 1000m+ above sea level — the highest vineyards in the Western Cape — the climate is dry, cold, and disease-free, producing grapes with intense flavour and natural acidity. Cederberg is the only estate in its ward, and its wines are uniquely high-altitude expressions.',
    awards: [{ body: 'Platter\'s', result: '5★', year: 2024, wine: 'Five Generations Cabernet Sauvignon' }],
    tastingRoom: 'Open Mon–Fri · 09:00–17:00', sustainabilityNote: 'IPW. Zero-use of fungicides at altitude.',
  },
  { id: 'e30', slug: 'diemersfontein', name: 'Diemersfontein', region: 'Wellington', wineRoute: 'Wellington Wine Route', founded: 1970, about: 'Famous for "coffee Pinotage" — the original chocolate/coffee style.', famousFor: 'Coffee Pinotage; Carpe Diem', verified: true, certifications: ['WO', 'IPW', 'WIETA'], lat: -33.65, lng: 18.9833, website: 'https://www.diemersfontein.co.za/',
    history: 'Diemersfontein shot to fame with its "Coffee Pinotage" — a style where specific oak staves impart coffee/chocolate notes, making Pinotage accessible to a mainstream audience. While divisive among purists, it became one of SA\'s most commercially successful Pinotage styles and introduced thousands of new drinkers to the variety. The Carpe Diem range represents the estate\'s more traditional, serious expressions.',
    awards: [{ body: 'Veritas', result: 'Gold', year: 2023, wine: 'Carpe Diem Pinotage' }],
    tastingRoom: 'Open daily · 10:00–16:00', sustainabilityNote: 'IPW + WIETA.',
  },
];

export const MOCK_WINES: MockWine[] = [
  { id: 'w1', slug: 'kanonkop-pinotage-2021', name: 'Kanonkop Pinotage', estateId: 'e1', estateName: 'Kanonkop', type: 'red', varietals: ['pinotage'], region: 'Simonsberg-Stellenbosch', avgStars: 4.5, ratingCount: 2847, priceZar: 420, abv: 14, year: 2021, about: 'The wine that proved Pinotage belongs among the world\'s noble reds. From the Sauer family\'s Simonsberg slopes — the same farm that pioneered the variety in 1925 — winemaker Abrie Beeslaar ferments in open concrete "kuipe" with punch-downs by foot. The result is unapologetically powerful: black plum, banana skin, damp earth, and a structural tannin frame that rewards 10–15 years in the cellar. A benchmark every SA wine drinker should taste at least once.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label, barcode: '6001234567890' },
  { id: 'w2', slug: 'klein-constantia-vin-de-constance-2019', name: 'Vin de Constance', estateId: 'e2', estateName: 'Klein Constantia', type: 'dessert', varietals: ['chenin-blanc'], region: 'Constantia', avgStars: 4.8, ratingCount: 1203, priceZar: 980, abv: 14, year: 2019, about: 'A resurrected legend. When Simon van der Stel planted Constantia in 1685, he could not have known his Muscat-based natural sweet wine would become the most coveted in 19th-century Europe — requested by Napoleon on his deathbed, written of by Dickens and Jane Austen. After phylloxera killed the vines, the wine vanished for a century. In the 1980s, Klein Constantia traced the original Muscat de Frontignan clones, replanted the steep sea-facing slopes, and painstakingly recreated it. The 2019 is all orange marmalade, apricot, honey and linden blossom — luscious yet poised, with an acidity that keeps it ethereal. Drink it slowly, slightly chilled, and taste history.', pairings: suggestPairings('dessert').slice(0, 3), serving: servingTempFor('dessert').label },
  { id: 'w3', slug: 'sadie-columella-2020', name: 'Sadie Columella', estateId: 'e3', estateName: 'Sadie Family Wines', type: 'red', varietals: ['shiraz', 'mourvedre', 'grenache'], region: 'Paardeberg (Swartland)', avgStars: 4.9, ratingCount: 412, priceZar: 1850, abv: 13.5, year: 2020, about: 'The wine that announced Eben Sadie — and the Swartland — to the world. Named for Lucius Columella, the Roman agricultural writer, this Rhône-influenced blend is sourced from ancient dryland bush vines on the decomposed granite of the Paardeberg. The 2020 vintage was a cool, balanced year that allowed extraordinary flavour concentration without excess ripeness. Expect profound depth: blackberry, white pepper, fynbos herb, crushed rock, and cured meat, wrapped in fine-grained tannin. It demands time — a decade in a good cellar rewards with layers that few South African wines can match. Each bottle carries an all-Latin label, befitting a wine of classical ambition.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w4', slug: 'sadie-skurfberg-chenin-2021', name: 'Sadie Skurfberg', estateId: 'e3', estateName: 'Sadie Family Wines', type: 'white', varietals: ['chenin-blanc'], region: 'Citrusdal Mountain', avgStars: 4.8, ratingCount: 286, priceZar: 1450, abv: 12.5, year: 2021, about: 'From a windswept, iron-rich hilltop in the Citrusdal Mountain ward — vines planted in 1962, surviving without irrigation in one of the harshest old-vine sites in the Cape. Eben Sadie considers these dryland bush vines a national treasure; they carry the Old Vine Project\'s Heritage seal, displaying the planting year on the bottle. The 2021 was an exceptional cool vintage that preserved razor acidity. The wine itself is a meditation: salted honey, dried apricot, beeswax, wet stone, and a finish that seems to last for minutes. It is Chenin Blanc as fine art — a strong argument that SA\'s old vines produce whites to rival any in the world.', pairings: suggestPairings('white', { varietalSlug: 'chenin-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w5', slug: 'hamilton-russell-pinot-noir-2022', name: 'Hamilton Russell Pinot Noir', estateId: 'e4', estateName: 'Hamilton Russell Vineyards', type: 'red', varietals: ['pinot-noir'], region: 'Hemel-en-Aarde Valley', avgStars: 4.6, ratingCount: 894, priceZar: 520, abv: 13, year: 2022, about: 'In 1975, Tim Hamilton Russell made a bet that seemed reckless: that the cold, wind-battered, most-southerly tip of Africa could produce world-class Pinot Noir. Half a century later, his son Anthony has proved him right. This is Hemel-en-Aarde at its purest — 8km from the sea, on clay-rich Bokkeveld shale, farmed single-mindedly for just Pinot Noir and Chardonnay. The 2022 is finely boned: red cherry, forest floor, mushroom, dried rose, and a savoury minerality that speaks directly of the maritime site. There is no artifice here — just a committed family, one cool valley, and the most food-friendly red in the Cape. Drink with duck, with mushroom risotto, or simply with patience.', pairings: suggestPairings('red', { varietalSlug: 'pinot-noir' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w6', slug: 'chocolate-block-2021', name: 'The Chocolate Block', estateId: 'e5', estateName: 'Boekenhoutskloof', type: 'red', varietals: ['shiraz', 'grenache', 'cinsaut', 'mourvedre'], region: 'Franschhoek', avgStars: 4.6, ratingCount: 15420, priceZar: 380, abv: 14.5, year: 2021, about: 'The blend that opened the door for premium South African wine on the world stage. When Marc Kent first assembled it in 2000, Rhône-style blends were rare in the Cape; today "Choc Block" is one of the most recognised SA wine names globally. Syrah-led with Grenache, Cinsaut and Mourvèdre, it is sourced from certified-sustainable Swartland and Franschhoek vineyards. The 2021 pours deeply coloured and generous — dark plum, white pepper, smoked meat, liquorice and a characteristic dark-chocolate undertone that gives the wine its name. It is, above all, a pleasure to drink young, yet the best vintages will reward five to eight years of age. A modern classic that proved SA blends can travel.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w7', slug: 'graham-beck-brut-rose', name: 'Graham Beck Brut Rosé MCC', estateId: 'e6', estateName: 'Graham Beck', type: 'sparkling', varietals: ['mcc'], region: 'Robertson', avgStars: 4.5, ratingCount: 3120, priceZar: 240, abv: 12.5, year: 0, about: 'Méthode Cap Classique — South Africa\'s answer to Champagne, made the traditional way: bottle fermentation, hand-riddling, months on lees. Graham Beck\'s Robertson cellar sits on limestone soils that mirror Champagne\'s chalk, and cellar-master Pieter "Bubbles" Ferreira has overseen every vintage for three decades. This Brut Rosé — Pinot Noir and Chardonnay — was famously poured at Nelson Mandela\'s 1994 inauguration and again at Barack Obama\'s 2008 election night. Expect a pale salmon hue, fine persistent mousse, red berry, brioche and a clean, mineral finish. It is, quietly, the Cape\'s most political wine — and one of its most consistent.', pairings: suggestPairings('sparkling', { isSparkling: true }).slice(0, 4), serving: servingTempFor('sparkling').label },
  { id: 'w8', slug: 'the-fmc-2019', name: 'Ken Forrester The FMC', estateId: 'e7', estateName: 'Ken Forrester', type: 'white', varietals: ['chenin-blanc'], region: 'Stellenbosch', avgStars: 4.7, ratingCount: 1856, priceZar: 420, abv: 14, year: 2019, about: 'The wine that earned Ken Forrester his "Mr Chenin Blanc" title. Made in partnership with winemaker Martin Meinert from old, low-yielding bush vines on the 1689 Zandberg farm outside Stellenbosch, The FMC (Forrester Meinert Chenin) is barrel-fermented, given extended lees contact and aged in French oak. The aim is unapologetic richness — and it succeeds. Dried apricot, honeycomb, toasted almond, beeswax and ripe pineapple, with a glycerol texture that coats the palate. Yet, crucially, the natural acidity of old-vine Chenin keeps it from cloying. It is a serious, ageworthy white — 10 years in a good cellar is not too long — and a benchmark for what South African Chenin can be when ambition meets the right old vines.', pairings: suggestPairings('white', { varietalSlug: 'chenin-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w9', slug: 'mullineux-syrah-2021', name: 'Mullineux Syrah', estateId: 'e8', estateName: 'Mullineux', type: 'red', varietals: ['shiraz'], region: 'Swartland', avgStars: 4.8, ratingCount: 743, priceZar: 580, abv: 13.5, year: 2021, about: 'Andrea Mullineux was at the centre of the Swartland revolution from its first vintages — a Californian who came to study, stayed, and now makes some of the Cape\'s most precise reds. Her Syrah is sourced from a single parcel of dryland bush vines on the rocky, decomposed-shale soils that define the region. Each parcel is vinified separately and aged in older French oak, so the wood never dominates. The 2021 is a cool-vintage Syrah of real finesse: blackberry, white pepper, fynbos herb, a meaty savouriness and fine, almost chalky tannin. It is not the biggest Swartland red — it is the most articulate. With time in the glass it unfolds for hours. A wine to make the case that the Swartland produces Syrah as serious as the Northern Rhône.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w10', slug: 'vergelegen-gvb-red-2018', name: 'Vergelegen GVB Red', estateId: 'e9', estateName: 'Vergelegen', type: 'red', varietals: ['bordeaux-blend'], region: 'Stellenbosch', avgStars: 4.7, ratingCount: 612, priceZar: 780, abv: 14.5, year: 2018, about: 'From one of South Africa\'s most historic estates — founded in 1700 by Governor Willem van der Stel, restored by Anglo American in 1987, and now consistently ranked among the country\'s top farms. The GVB (Gran Vergelegen) Red is the flagship Bordeaux-style blend, Cabernet Sauvignon-led with Merlot, Cabernet Franc and Petit Verdot, grown on the estate\'s heldeberg-amphitheatre vineyards. The 2018 vintage followed the Cape drought years — small yields, intense concentration. The wine is structured and age-worthy: cassis, cedar pencil, graphite, dark chocolate and firm, ripe tannin. It is built for the long haul — give it a decade and it will repay with classic, claret-like poise. A reminder that the Cape can do serious, structured, old-world reds.', pairings: suggestPairings('red', { varietalSlug: 'bordeaux-blend' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w11', slug: 'iona-sauvignon-blanc-2022', name: 'Iona Sauvignon Blanc', estateId: 'e10', estateName: 'Iona', type: 'white', varietals: ['sauvignon-blanc'], region: 'Elgin', avgStars: 4.6, ratingCount: 1024, priceZar: 280, abv: 13, year: 2022, about: 'In 1997, Andrew Gunn bought a remote 420-hectare property in the Elgin valley, 420 metres up and within sight of the Atlantic. His bet — that this cold, slow-ripening, Kogelberg-biosphere site could produce Sauvignon Blanc of uncommon elegance — has become one of the defining stories of the Cape\'s cool-climate frontier. The 2022 is a textbook example: nettle, passion fruit, green fig, lime zest and a flinty mineral edge, all carried by a bracing natural acidity that feels almost electric. It is one of the most restrained, food-friendly Sauvignon Blancs in the country — proof that the Cape\'s future lies not just in warm reds but in the cool highlands and coast. Drink it young, well chilled, with oysters or goat cheese.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  // ── 30 NEW WINES (w12–w41) for the 20 new estates ────────────────────────
  { id: 'w12', slug: 'meerlust-rubicon-2020', name: 'Meerlust Rubicon', estateId: 'e11', estateName: 'Meerlust', type: 'red', varietals: ['bordeaux-blend'], region: 'Stellenbosch', avgStars: 4.7, ratingCount: 3201, priceZar: 650, abv: 14.5, year: 2020, about: 'The wine that defined SA Bordeaux blends. Named after the Rubicon river — Hanni Myburgh\'s father declared the estate had "crossed the Rubicon" when they first bottled it in 1980. A Cabernet-led blend with Merlot, Cabernet Franc and Petit Verdot from the estate\'s false-bay-influenced vineyards. The 2020 is classic Rubicon: cassis, cedar, graphite, dark plum, and a structured, age-worthy tannin frame. One of the most consistently excellent icon wines in SA.', pairings: suggestPairings('red', { varietalSlug: 'bordeaux-blend' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w13', slug: 'meerlust-cabernet-sauvignon-2020', name: 'Meerlust Cabernet Sauvignon', estateId: 'e11', estateName: 'Meerlust', type: 'red', varietals: ['cabernet-sauvignon'], region: 'Stellenbosch', avgStars: 4.5, ratingCount: 1842, priceZar: 520, abv: 14.5, year: 2020, about: 'Meerlust\'s varietal Cabernet Sauvignon — from the same false-bay-influenced vineyards as Rubicon. Structured, firm, classic Stellenbosch Cab: cassis, eucalyptus, dark chocolate, and a tannin grip that rewards 5-10 years of patience.', pairings: suggestPairings('red', { varietalSlug: 'cabernet-sauvignon' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w14', slug: 'rustenberg-peter-barlow-2019', name: 'Rustenberg Peter Barlow Cabernet', estateId: 'e12', estateName: 'Rustenberg', type: 'red', varietals: ['cabernet-sauvignon'], region: 'Stellenbosch', avgStars: 4.6, ratingCount: 936, priceZar: 580, abv: 14.5, year: 2019, about: 'Named after Peter Barlow, who bought Rustenberg in 1941 and restored it. This single-vineyard Cabernet Sauvignon from the estate\'s oldest Cabernet block (planted 1948) is one of SA\'s longest-lived reds. Cassis, cedar, tobacco, eucalyptus, and a backbone of ripe tannin that demands decanting now or a decade in the cellar.', pairings: suggestPairings('red', { varietalSlug: 'cabernet-sauvignon' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w15', slug: 'rustenberg-chardonnay-2022', name: 'Rustenberg Chardonnay', estateId: 'e12', estateName: 'Rustenberg', type: 'white', varietals: ['chardonnay'], region: 'Stellenbosch', avgStars: 4.4, ratingCount: 682, priceZar: 280, abv: 13.5, year: 2022, about: 'A Stellenbosch Chardonnay benchmark. Barrel-fermented with natural malolactic, aged 9 months in French oak. Citrus, stone fruit, hazelnut, butter — well-integrated oak, bright acid. Consistently rated among SA\'s top Chardonnays at this price point.', pairings: suggestPairings('white', { varietalSlug: 'chardonnay' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w16', slug: 'thelema-sauvignon-blanc-2023', name: 'Thelema Sauvignon Blanc', estateId: 'e13', estateName: 'Thelema', type: 'white', varietals: ['sauvignon-blanc'], region: 'Stellenbosch', avgStars: 4.3, ratingCount: 1456, priceZar: 220, abv: 13.5, year: 2023, about: 'Thelema\'s flagship white — from the Helshoogte Pass vineyards. Crisp, herbaceous, gooseberry and nettle with a mineral finish. One of the best-value serious Sauvignon Blancs from Stellenbosch.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w17', slug: 'simonsig-kaapse-vonkel-brut', name: 'Simonsig Kaapse Vonkel Brut', estateId: 'e14', estateName: 'Simonsig', type: 'sparkling', varietals: ['mcc'], region: 'Stellenbosch', avgStars: 4.4, ratingCount: 2104, priceZar: 220, abv: 12.5, year: 0, about: 'The original SA Cap Classique — first produced in 1971 by Frans Malan, predating every other MCC. Pinot Noir + Chardonnay, traditional method, aged on lees. Fine mousse, green apple, brioche, almond. The wine that started SA\'s sparkling revolution, still one of the best-value MCCs.', pairings: suggestPairings('sparkling', { isSparkling: true }).slice(0, 4), serving: servingTempFor('sparkling').label },
  { id: 'w18', slug: 'simonsig-pinotage-2021', name: 'Simonsig Pinotage', estateId: 'e14', estateName: 'Simonsig', type: 'red', varietals: ['pinotage'], region: 'Stellenbosch', avgStars: 4.2, ratingCount: 892, priceZar: 240, abv: 14, year: 2021, about: 'Simonsig\'s Pinotage from the Simonsberg slopes. Ripe plum, banana, mocha, and integrated oak. Good value introduction to the variety from a pioneer estate.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w19', slug: 'boschendal-1685-blend-2020', name: 'Boschendal 1685 Cabernet Sauvignon', estateId: 'e15', estateName: 'Boschendal', type: 'red', varietals: ['cabernet-sauvignon'], region: 'Stellenbosch', avgStars: 4.1, ratingCount: 1623, priceZar: 185, abv: 14, year: 2020, about: 'Named for the estate\'s founding year. A classic Stellenbosch Cabernet at an accessible price. Blackcurrant, cedar, subtle oak, medium body. One of SA\'s best-value serious reds.', pairings: suggestPairings('red', { varietalSlug: 'cabernet-sauvignon' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w20', slug: 'warwick-three-cape-ladies-2020', name: 'Warwick Three Cape Ladies', estateId: 'e16', estateName: 'Warwick', type: 'red', varietals: ['pinotage', 'cabernet-sauvignon', 'merlot'], region: 'Stellenbosch', avgStars: 4.3, ratingCount: 1107, priceZar: 320, abv: 14, year: 2020, about: 'A Cape Blend — Pinotage, Cabernet Sauvignon, and Merlot. Pioneered by Norma Ratcliffe ("The First Lady of SA Wine"). Ripe berry, spice, mocha, soft tannin. Approachable and food-friendly — a true SA original style.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w21', slug: 'nederburg-ii-heroes-cabernet-2020', name: 'Nederburg II Heroes Cabernet', estateId: 'e17', estateName: 'Nederburg', type: 'red', varietals: ['cabernet-sauvignon'], region: 'Paarl', avgStars: 4.2, ratingCount: 3402, priceZar: 180, abv: 14, year: 2020, about: 'Part of Nederburg\'s premium "II Heroes" range, named after founder Johann Graue and his son. A structured, classic Paarl Cabernet: cassis, cedar, dark chocolate, firm tannin. Extraordinary value from SA\'s most-awarded winery.', pairings: suggestPairings('red', { varietalSlug: 'cabernet-sauvignon' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w22', slug: 'fairview-shiraz-2021', name: 'Fairview Shiraz', estateId: 'e18', estateName: 'Fairview', type: 'red', varietals: ['shiraz'], region: 'Paarl', avgStars: 4.3, ratingCount: 1788, priceZar: 220, abv: 14, year: 2021, about: 'Charles Back\'s Shiraz from Paarl granite soils. Black pepper, dark berry, white pepper, subtle oak. Consistently one of SA\'s best-value serious reds. Pair with the estate\'s famous artisanal cheese.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w23', slug: 'fairview-pinotage-2021', name: 'Fairview Pinotage', estateId: 'e18', estateName: 'Fairview', type: 'red', varietals: ['pinotage'], region: 'Paarl', avgStars: 4.0, ratingCount: 1243, priceZar: 165, abv: 14, year: 2021, about: 'A modern, fruit-forward Paarl Pinotage. Red plum, banana, chocolate, soft tannin. Accessible and food-friendly — great with a braai or the Fairview goat\'s cheese.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w24', slug: 'durbanville-hills-sauvignon-blanc-2023', name: 'Durbanville Hills Sauvignon Blanc', estateId: 'e19', estateName: 'Durbanville Hills', type: 'white', varietals: ['sauvignon-blanc'], region: 'Durbanville', avgStars: 4.1, ratingCount: 2890, priceZar: 150, abv: 13.5, year: 2023, about: 'Durbanville Hills\' flagship white — from cool maritime vineyards 20km from the Atlantic. Crisp nettle, gooseberry, passion fruit, lime. One of SA\'s best-value cool-climate Sauvignon Blancs. Consistently reliable.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w25', slug: 'de-grendel-sauvignon-blanc-2023', name: 'De Grendel Sauvignon Blanc', estateId: 'e20', estateName: 'De Grendel', type: 'white', varietals: ['sauvignon-blanc'], region: 'Durbanville', avgStars: 4.2, ratingCount: 1567, priceZar: 170, abv: 13, year: 2023, about: 'From the Graaff family estate with sweeping Table Bay views. Tropical and herbaceous — passion fruit, guava, green pepper, lime. Bright acid, clean finish. One of Durbanville\'s best everyday Sauvignon Blancs.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w26', slug: 'dewetshof-site-of-origin-chardonnay-2021', name: 'De Wetshof Site of Origin Chardonnay', estateId: 'e21', estateName: 'De Wetshof', type: 'white', varietals: ['chardonnay'], region: 'Robertson', avgStars: 4.5, ratingCount: 612, priceZar: 320, abv: 13.5, year: 2021, about: 'Danie de Wet\'s flagship Chardonnay — from a single limestone-rich vineyard in Robertson. Unwooded, fermented in stainless steel. Citrus, white peach, wet stone, and a chalky minerality that speaks directly of the limestone soils. One of SA\'s purest expressions of Chardonnay terroir.', pairings: suggestPairings('white', { varietalSlug: 'chardonnay' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w27', slug: 'springfield-life-from-stone-2022', name: 'Springfield Life from Stone Sauvignon Blanc', estateId: 'e22', estateName: 'Springfield Estate', type: 'white', varietals: ['sauvignon-blanc'], region: 'Robertson', avgStars: 4.6, ratingCount: 803, priceZar: 320, abv: 13.5, year: 2022, about: 'From a single vineyard of quartz-stone soils in Robertson. Wild-yeast fermented, unfiltered, unfined. The result is unlike any other SA Sauvignon Blanc — intense minerality, gunflint, green fig, white peach, and a texture that feels almost saline. It polarises (some find it "reduced") but the purists adore it. A wine with a cult following.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w28', slug: 'creation-pinot-noir-reserve-2022', name: 'Creation Pinot Noir Reserve', estateId: 'e23', estateName: 'Creation Wines', type: 'red', varietals: ['pinot-noir'], region: 'Hemel-en-Aarde Valley', avgStars: 4.5, ratingCount: 534, priceZar: 420, abv: 13.5, year: 2022, about: 'From the high ridge of the Hemel-en-Aarde Valley, JC Martin\'s Reserve Pinot Noir is one of the most consistent cool-climate Pinots in SA. Red cherry, forest floor, dried rose, mushroom, fine tannin. Aged 11 months in French oak (30% new). Elegant and age-worthy.', pairings: suggestPairings('red', { varietalSlug: 'pinot-noir' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w29', slug: 'creation-chardonnay-2023', name: 'Creation Chardonnay', estateId: 'e23', estateName: 'Creation Wines', type: 'white', varietals: ['chardonnay'], region: 'Hemel-en-Aarde Valley', avgStars: 4.4, ratingCount: 489, priceZar: 280, abv: 13, year: 2023, about: 'A Hemel-en-Aarde Chardonnay from the estate\'s high-altitude vineyards. Barrel-fermented, partial malolactic. Citrus, stone fruit, hazelnut, brioche, bright acid. A textbook cool-climate Chardonnay at a fair price.', pairings: suggestPairings('white', { varietalSlug: 'chardonnay' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w30', slug: 'bouchard-finlayson-galpin-peak-2020', name: 'Bouchard Finlayson Galpin Peak Pinot Noir', estateId: 'e24', estateName: 'Bouchard Finlayson', type: 'red', varietals: ['pinot-noir'], region: 'Hemel-en-Aarde Valley', avgStars: 4.7, ratingCount: 387, priceZar: 650, abv: 13.5, year: 2020, about: 'Named after the Galpin Peak mountain that towers over the vineyard. One of SA\'s most celebrated Pinot Noirs — from a single vineyard planted on Bokkeveld shale in 1989. Aged 10 months in French oak. Profound: dark cherry, forest floor, truffle, dried herb, fine-grained tannin. Only produced in exceptional vintages. A collector\'s Pinot.', pairings: suggestPairings('red', { varietalSlug: 'pinot-noir' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w31', slug: 'paul-cluver-pinot-noir-2022', name: 'Paul Cluver Pinot Noir', estateId: 'e25', estateName: 'Paul Cluver Wines', type: 'red', varietals: ['pinot-noir'], region: 'Elgin', avgStars: 4.4, ratingCount: 678, priceZar: 320, abv: 13, year: 2022, about: 'From the cool high-altitude Elgin plateau. One of the best-value serious Pinot Noirs in SA. Red cherry, raspberry, forest floor, earthy minerality. Partial whole-bunch fermentation adds structure. Consistently rated a top Elgin Pinot.', pairings: suggestPairings('red', { varietalSlug: 'pinot-noir' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w32', slug: 'paul-cluver-riesling-2022', name: 'Paul Cluver Riesling', estateId: 'e25', estateName: 'Paul Cluver Wines', type: 'white', varietals: ['riesling'], region: 'Elgin', avgStars: 4.5, ratingCount: 412, priceZar: 240, abv: 12, year: 2022, about: 'One of the very few serious Rieslings produced in South Africa. From cool Elgin vineyards. Off-dry with bracing acidity: lime, green apple, white peach, jasmine, and a distinct petrol note even in youth. Ages beautifully for 10-15+ years. A unique SA expression of a noble grape.', pairings: suggestPairings('white', { varietalSlug: 'riesling' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w33', slug: 'aa-badenhorst-secateurs-red-2022', name: 'AA Badenhorst Secateurs Red', estateId: 'e26', estateName: 'AA Badenhorst Family Wines', type: 'red', varietals: ['shiraz', 'grenache', 'cinsaut', 'mourvedre'], region: 'Swartland', avgStars: 4.3, ratingCount: 1893, priceZar: 240, abv: 13, year: 2022, about: 'Adi Badenhorst\'s everyday Swartland red — a Rhône-style blend (Shiraz, Grenache, Cinsaut, Mourvèdre) from old dryland bush vines. Whole-cluster fermented with native yeasts. Juicy, peppery, earthy: red cherry, black pepper, herbes du Cap, leather. One of the best-value natural-leaning reds in SA. Unfiltered.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w34', slug: 'aa-badenhorst-kalmoesfontein-red-2020', name: 'AA Badenhorst Kalmoesfontein Red', estateId: 'e26', estateName: 'AA Badenhorst Family Wines', type: 'red', varietals: ['shiraz', 'grenache', 'mourvedre'], region: 'Swartland', avgStars: 4.6, ratingCount: 324, priceZar: 580, abv: 13.5, year: 2020, about: 'The flagship of the Badenhorst family — named after the Paardeberg farm. Old-vine Shirah-led blend from dryland bush vines. Whole-bunch, natural yeast, aged in old oak foudres. Deep, savoury, structured: blackberry, white pepper, fynbos, game, and a fine, rocky tannin. A serious wine that demands food and time.', pairings: suggestPairings('red', { varietalSlug: 'shiraz' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w35', slug: 'spier-creative-block-5-2020', name: 'Spier Creative Block 5', estateId: 'e27', estateName: 'Spier', type: 'red', varietals: ['cabernet-sauvignon', 'merlot', 'shiraz', 'malbec', 'petit-verdot'], region: 'Stellenbosch', avgStars: 4.2, ratingCount: 945, priceZar: 280, abv: 14, year: 2020, about: 'A five-varietal Bordeaux-meets-Rhône blend from Spier. Each year the winemaker selects the best 5 barrels from different varieties. Ripe, generous: black plum, cassis, spice, vanilla. Accessible and broad-appeal. Great value for a serious blend.', pairings: suggestPairings('red', { varietalSlug: 'bordeaux-blend' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w36', slug: 'boplaas-cape-tawny', name: 'Boplaas Cape Tawny', estateId: 'e28', estateName: 'Boplaas', type: 'fortified', varietals: ['touriga-nacional', 'tinta-barroca'], region: 'Calitzdorp', avgStars: 4.5, ratingCount: 678, priceZar: 350, abv: 18, year: 0, about: 'The benchmark SA port-style wine — aged oxidatively in old oak barrels for years, like a Tawny Port. Tinta Barroca and Touriga Nacional from Calitzdorp. Caramel, walnut, dried fig, orange peel, toffee. Serve slightly chilled with nuts or dark chocolate. The wine that put Calitzdorp on the SA map.', pairings: suggestPairings('dessert').slice(0, 3), serving: servingTempFor('fortified').label },
  { id: 'w37', slug: 'boplaas-cape-vintage-reserve-2020', name: 'Boplaas Cape Vintage Reserve', estateId: 'e28', estateName: 'Boplaas', type: 'fortified', varietals: ['touriga-nacional', 'tinta-barroca'], region: 'Calitzdorp', avgStars: 4.6, ratingCount: 423, priceZar: 420, abv: 19, year: 2020, about: 'The flagship fortified from SA\'s "port capital." Made in declared-vintage years only, from old Portuguese varieties. Dense, powerful, dark: black plum, dark chocolate, liquorice, spice. Will age 20-30+ years. Decant before serving with blue cheese.', pairings: suggestPairings('dessert').slice(0, 3), serving: servingTempFor('fortified').label },
  { id: 'w38', slug: 'cederberg-five-generations-cabernet-2019', name: 'Cederberg Five Generations Cabernet Sauvignon', estateId: 'e29', estateName: 'Cederberg Private Cellar', type: 'red', varietals: ['cabernet-sauvignon'], region: 'Cederberg', avgStars: 4.7, ratingCount: 298, priceZar: 650, abv: 14.5, year: 2019, about: 'The pinnacle of the Cederberg range — named for the five Nieuwoudt generations who have farmed these 1000m+ mountain vineyards. From the estate\'s best Cabernet block. Aged 18 months in new French oak. Intensely concentrated: blackcurrant, cedar, eucalyptus, dark chocolate, graphite. Firm, ripe tannin. Unique high-altitude expression found nowhere else in SA.', pairings: suggestPairings('red', { varietalSlug: 'cabernet-sauvignon' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w39', slug: 'cederberg-sauvignon-blanc-2023', name: 'Cederberg Sauvignon Blanc', estateId: 'e29', estateName: 'Cederberg Private Cellar', type: 'white', varietals: ['sauvignon-blanc'], region: 'Cederberg', avgStars: 4.4, ratingCount: 1234, priceZar: 195, abv: 13.5, year: 2023, about: 'From the highest vineyards in the Western Cape (1000m+). The extreme altitude gives intense flavour concentration and bracing natural acidity. Passion fruit, gooseberry, nettle, lime, a flinty mineral edge. Clean, crisp, unoaked. A unique SA Sauvignon Blanc that reflects its mountain terroir.', pairings: suggestPairings('white', { varietalSlug: 'sauvignon-blanc' }).slice(0, 4), serving: servingTempFor('white').label },
  { id: 'w40', slug: 'diemersfontein-coffee-pinotage-2022', name: 'Diemersfontein Coffee Pinotage', estateId: 'e30', estateName: 'Diemersfontein', type: 'red', varietals: ['pinotage'], region: 'Wellington', avgStars: 4.0, ratingCount: 2456, priceZar: 185, abv: 14, year: 2022, about: 'The original "coffee Pinotage" — the wine that polarised SA wine lovers. A specific oak regime imparts distinct coffee and dark-chocolate notes to Pinotage\'s natural plum and banana fruit. Love it or hate it, it introduced thousands of new drinkers to the variety. Accessible, crowd-pleasing, unapologetically commercial.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label },
  { id: 'w41', slug: 'diemersfontein-carpe-diem-pinotage-2020', name: 'Diemersfontein Carpe Diem Pinotage', estateId: 'e30', estateName: 'Diemersfontein', type: 'red', varietals: ['pinotage'], region: 'Wellington', avgStars: 4.3, ratingCount: 412, priceZar: 320, abv: 14.5, year: 2020, about: 'The serious, traditional Pinotage — the one Diemersfontein makes for purists who find the "Coffee" style too much. From old bush vines, aged in French oak. Plum, blackberry, earth, leather, integrated oak, structured tannin. A proper, age-worthy Pinotage that shows the variety at its most traditional.', pairings: suggestPairings('red', { varietalSlug: 'pinotage' }).slice(0, 4), serving: servingTempFor('red').label },
];

export const MOCK_EVENTS = [
  // ── JANUARY ──────────────────────────────────────────────────────────────
  { id: 'ev1', name: 'Hemel-en-Aarde Pinot Noir Celebration', slug: 'hemel-pinot-2026', description: 'Premium Pinot Noir showcase — one of SA\'s top cool-climate tastings, hosted by the Hemel-en-Aarde producers in Hermanus.', startsAt: '2026-01-24', endsAt: '2026-01-25', venueName: 'Hermanus / Hemel-en-Aarde Valley', ticketingPlatform: 'Direct', format: 'grand-tasting', recurringMonth: 1 },
  // ── FEBRUARY ─────────────────────────────────────────────────────────────
  { id: 'ev2', name: 'Cape Wine Auction', slug: 'cape-wine-auction-2026', description: 'High-profile charity auction raising millions for wine-region education, hosted at Nederburg.', startsAt: '2026-02-14', endsAt: '2026-02-14', venueName: 'Nederburg Wine Estate, Paarl', ticketUrl: 'https://thecapewineauction.com/', ticketingPlatform: 'Direct', priceMinZar: 1500, priceMaxZar: 0, format: 'trade-show', recurringMonth: 2 },
  { id: 'ev3', name: 'Simonsberg Wine Festival (RMB)', slug: 'simonsberg-wine-fest-2026', description: 'Showcase of Simonsberg-region wines with live music and gourmet food, paired with the RMB Run4Rivers trail run.', startsAt: '2026-02-21', endsAt: '2026-02-21', venueName: 'Plaisir Wine Estate, Simondium', ticketUrl: 'https://simonsbergwinefestival.co.za/', ticketingPlatform: 'Quicket', priceMinZar: 350, priceMaxZar: 350, format: 'grand-tasting', recurringMonth: 2 },
  { id: 'ev4', name: 'Nederburg Harvest Festival', slug: 'nederburg-harvest-2026', description: 'Hands-on grape-stomp and harvest-celebration evening at one of Paarl\'s historic estates.', startsAt: '2026-02-28', endsAt: '2026-02-28', venueName: 'Nederburg Wine Estate, Paarl', ticketingPlatform: 'Direct', priceMinZar: 1495, priceMaxZar: 1495, format: 'open-cellars', recurringMonth: 2 },
  // ── MARCH ────────────────────────────────────────────────────────────────
  { id: 'ev5', name: 'BOTFEST (Bot River Wine Festival)', slug: 'botfest-2026', description: 'Single-venue gathering of 20+ Bot River producers at Gabriëlskloof; the modern successor to the old hop-between festival.', startsAt: '2026-03-21', endsAt: '2026-03-21', venueName: 'Gabriëlskloof Wine Estate, Bot River', ticketUrl: 'https://www.quicket.co.za/events/340564-botfest-2026/', ticketingPlatform: 'Quicket', priceMinZar: 800, priceMaxZar: 800, format: 'grand-tasting', recurringMonth: 3 },
  { id: 'ev6', name: 'Franschhoek Summer Wines', slug: 'franschhoek-summer-2026', description: 'Summer lifestyle wine tasting at Leopard\'s Leap with a "White Summer Elegance" dress theme.', startsAt: '2026-03-07', endsAt: '2026-03-07', venueName: 'Leopard\'s Leap Family Vineyards, Franschhoek', ticketUrl: 'https://franschhoek.org.za/events/', ticketingPlatform: 'Webtickets', priceMinZar: 350, priceMaxZar: 350, format: 'grand-tasting', recurringMonth: 3 },
  // ── APRIL ────────────────────────────────────────────────────────────────
  { id: 'ev7', name: 'Pick n Pay Wine & Food Festival — Cape Town', slug: 'pnp-wine-cape-town-2026', description: '60+ wine-stand walk-around tasting with food, live music, and PnP Liquor Mixology Theatre.', startsAt: '2026-04-25', endsAt: '2026-04-26', venueName: 'Claremont Cricket Club, Cape Town', ticketUrl: 'https://www.pnpwineandfoodfestival.co.za/events/capetown/', ticketingPlatform: 'Direct', priceMinZar: 350, priceMaxZar: 350, format: 'trade-show', recurringMonth: 4 },
  { id: 'ev8', name: 'Elgin Railway Wine Festival', slug: 'elgin-railway-2026', description: '12 Elgin and Bot River producers pour at the voted-best-market in the Western Cape.', startsAt: '2026-04-12', endsAt: '2026-04-12', venueName: 'Elgin Railway Market, Elgin Valley', ticketUrl: 'https://www.elginrailwaymarket.co.za/elgin-winter-wine-festival/', ticketingPlatform: 'Webtickets', priceMinZar: 280, priceMaxZar: 295, format: 'grand-tasting', recurringMonth: 4 },
  { id: 'ev9', name: 'Agulhas Wine Triangle Festival', slug: 'agulhas-fest-2026', description: 'Southernmost wine-region harvest festival with masterclasses from the Agulhas triangle producers.', startsAt: '2026-04-19', endsAt: '2026-04-19', venueName: 'Lomond Wine Estate, Gansbaai', ticketUrl: 'https://agulhaswinetriangle.co.za/festival/', ticketingPlatform: 'Quicket', priceMinZar: 250, priceMaxZar: 300, format: 'grand-tasting', recurringMonth: 4 },
  // ── MAY ──────────────────────────────────────────────────────────────────
  { id: 'ev10', name: 'Sip & Savour @ The Mountains', slug: 'sip-savour-mountains-2026', description: 'Robertson Valley\'s winter slow-food-and-wine weekend (formerly Robertson Slow) with 17+ wine farms.', startsAt: '2026-05-16', endsAt: '2026-05-18', venueName: 'Robertson Wine Valley', ticketUrl: 'https://robertsonwinevalley.com/events/', ticketingPlatform: 'Webtickets', priceMinZar: 250, priceMaxZar: 500, format: 'open-cellars', recurringMonth: 5 },
  { id: 'ev11', name: 'Netwerk24 en Die Burger Wynproefees', slug: 'burger-wynproefees-2026', description: 'Afrikaans-newspaper flagship walk-around wine tasting in the Durbanville hills.', startsAt: '2026-05-23', endsAt: '2026-05-23', venueName: 'Meerendal Wine Estate, Durbanville', ticketUrl: 'https://www.quicket.co.za/events/362431', ticketingPlatform: 'Quicket', priceMinZar: 350, priceMaxZar: 350, format: 'grand-tasting', recurringMonth: 5 },
  // ── JUNE ─────────────────────────────────────────────────────────────────
  { id: 'ev12', name: 'Robertson Wacky Wine Weekend', slug: 'wacky-wine-2026', description: 'Massive valley-wide open-cellars weekend. 40+ wineries, hop-between-estates format. One of SA\'s biggest consumer wine events.', startsAt: '2026-06-04', endsAt: '2026-06-07', venueName: 'Robertson / Breede River Valley', ticketUrl: 'https://robertsonwinevalley.com/events/', ticketingPlatform: 'Webtickets', priceMinZar: 250, priceMaxZar: 500, format: 'open-cellars', recurringMonth: 6 },
  { id: 'ev13', name: 'Calitzdorp Expressed', slug: 'calitzdorp-expressed-2026', description: 'Celebration of South Africa\'s port-style wine capital (formerly Calitzdorp Port & Wine Festival), with cellar tours and regional cuisine.', startsAt: '2026-06-21', endsAt: '2026-06-21', venueName: 'Calitzdorp, Klein Karoo', ticketUrl: 'https://visitcalitzdorp.co.za/event/calitzdorp-expressed/', ticketingPlatform: 'Quicket', priceMinZar: 200, priceMaxZar: 200, format: 'open-cellars', recurringMonth: 6 },
  { id: 'ev14', name: 'Chenin Blanc Festival', slug: 'chenin-blanc-fest-2026', description: 'The Chenin Blanc Association\'s flagship tasting of SA\'s most planted varietal. Includes branded Drink Chenin glass.', startsAt: '2026-06-14', endsAt: '2026-06-14', venueName: 'Cavalli Wine Estate, Somerset West', ticketUrl: 'https://www.chenin.co.za/events', ticketingPlatform: 'Direct', priceMinZar: 450, priceMaxZar: 450, format: 'grand-tasting', recurringMonth: 6 },
  // ── JULY ─────────────────────────────────────────────────────────────────
  { id: 'ev15', name: 'Wine Town Stellenbosch', slug: 'wine-town-2026', description: 'SA\'s premier wine destination festival — 60+ producers, 200+ wines, marking 55 years of Stellenbosch Wine Routes. 9-day programme across the region.', startsAt: '2026-07-25', endsAt: '2026-08-02', venueName: 'Stellenbosch Town Hall + estates', ticketUrl: 'https://winetown.wineroute.co.za/', ticketingPlatform: 'Own portal', priceMinZar: 600, priceMaxZar: 650, format: 'grand-tasting', recurringMonth: 7 },
  { id: 'ev16', name: 'Stellenbosch Wine Festival', slug: 'stellenbosch-fest-2026', description: 'The flagship grand tasting at the heart of Wine Town: 60+ producers, bottomless food by Bertus Basson, 20 tasting tokens.', startsAt: '2026-07-31', endsAt: '2026-08-01', venueName: 'Stellenbosch Town Hall', ticketUrl: 'https://winetown.wineroute.co.za/wine-festival/', ticketingPlatform: 'Own portal', priceMinZar: 600, priceMaxZar: 650, format: 'grand-tasting', recurringMonth: 7 },
  { id: 'ev17', name: 'Knysna Fine Wine Festival', slug: 'knysna-wine-2026', description: 'Premium curated tasting — the flagship wine event of the 10-day Knysna Oyster Festival.', startsAt: '2026-07-11', endsAt: '2026-07-11', venueName: 'Loerie Park Sportsfield, Knysna', ticketUrl: 'https://www.quicket.co.za/events/371973', ticketingPlatform: 'Quicket', priceMinZar: 300, priceMaxZar: 350, format: 'grand-tasting', recurringMonth: 7 },
  { id: 'ev18', name: 'Franschhoek Bastille Festival', slug: 'franschhoek-bastille-2026', description: 'French-heritage winter celebration with wine-and-cheese tastings themed around Bastille Day.', startsAt: '2026-07-12', endsAt: '2026-07-13', venueName: 'Franschhoek High School grounds', ticketUrl: 'https://franschhoekbastille.co.za/', ticketingPlatform: 'Webtickets', priceMinZar: 400, priceMaxZar: 450, format: 'grand-tasting', recurringMonth: 7 },
  { id: 'ev19', name: 'Greyton Fire + Wine', slug: 'greyton-fire-wine-2026', description: 'Hop-between tasting route through Greyton\'s restaurants and guesthouses. Riedel glass included.', startsAt: '2026-07-26', endsAt: '2026-07-27', venueName: 'Greyton village', ticketUrl: 'https://greytontourism.com/product/greyton-firewine-2026/', ticketingPlatform: 'Quicket', priceMinZar: 690, priceMaxZar: 740, format: 'hop-between', recurringMonth: 7 },
  { id: 'ev20', name: 'TOPS at SPAR Wine Show', slug: 'tops-spar-2026', description: 'Multi-city consumer walk-around tasting tour. 200+ wines, all-inclusive glass. Visits Cape Town, Joburg, Pretoria, Durban.', startsAt: '2026-07-17', endsAt: '2026-07-18', venueName: 'Multi-city tour', ticketingPlatform: 'Quicket', priceMinZar: 200, priceMaxZar: 350, format: 'grand-tasting', recurringMonth: 7 },
  { id: 'ev21', name: 'Annerkant die Berg (Breedekloof)', slug: 'annerkant-die-berg-2026', description: 'Rebranded Breedekloof winter wine-and-outdoor festival across multiple valley wineries.', startsAt: '2026-07-05', endsAt: '2026-07-06', venueName: 'Breedekloof Wine Valley (Rawsonville)', ticketUrl: 'https://www.breedekloof.com/', ticketingPlatform: 'Computicket', priceMinZar: 200, priceMaxZar: 400, format: 'open-cellars', recurringMonth: 7 },
  // ── AUGUST ───────────────────────────────────────────────────────────────
  { id: 'ev22', name: 'Klein Karoo Klassique', slug: 'klein-karoo-klassique-2026', description: 'Winter festival of classical music, literature, art, food, and Klein Karoo wine.', startsAt: '2026-08-07', endsAt: '2026-08-09', venueName: 'Oudtshoorn (town centre)', ticketUrl: 'https://www.klassique.co.za/eng/', ticketingPlatform: 'Quicket', priceMinZar: 100, priceMaxZar: 130, format: 'grand-tasting', recurringMonth: 8 },
  { id: 'ev23', name: 'Pick n Pay Wine & Food Festival — Johannesburg', slug: 'pnp-wine-jozi-2026', description: 'Joburg leg of the PnP tour, debuting the Diageo Mixology Theatre.', startsAt: '2026-08-23', endsAt: '2026-08-23', venueName: 'The Wanderers Club, Illovo, Johannesburg', ticketUrl: 'https://www.pnpwineandfoodfestival.co.za/events/jozi/', ticketingPlatform: 'Direct', priceMinZar: 350, priceMaxZar: 350, format: 'trade-show', recurringMonth: 8 },
  { id: 'ev24', name: 'Franschhoek Cap Classique Safari', slug: 'cap-classique-safari-2026', description: 'Guided/self-drive safari visiting five MCC producers with optional paired lunch.', startsAt: '2026-08-30', endsAt: '2026-08-31', venueName: 'Franschhoek estates (hop between)', ticketUrl: 'https://franschhoek.org.za/franschhoek-cap-classique-safari/', ticketingPlatform: 'Direct', priceMinZar: 750, priceMaxZar: 1100, format: 'hop-between', recurringMonth: 8 },
  // ── SEPTEMBER ────────────────────────────────────────────────────────────
  { id: 'ev25', name: 'Blomme & Bubbles Festival', slug: 'blomme-bubbles-2026', description: 'Coastal spring festival pairing 30+ wineries (200+ wines, Cap Classique focus) with local art and music.', startsAt: '2026-09-12', endsAt: '2026-09-14', venueName: 'Paternoster Wine & Tasting Lounge, West Coast', ticketUrl: 'https://paternosterwinelounge.co.za/blommebubbles', ticketingPlatform: 'Howler', priceMinZar: 450, priceMaxZar: 450, format: 'grand-tasting', recurringMonth: 9 },
  { id: 'ev26', name: 'Swartland Olive & Wine Festival', slug: 'swartland-olive-2026', description: 'Mediterranean-flavoured celebration of the Swartland olive harvest with olive oil, wine, and food stalls.', startsAt: '2026-09-25', endsAt: '2026-09-27', venueName: 'Town Square, Riebeek-Kasteel', ticketUrl: 'https://swartlandtourism.co.za/swartland-olive-festival/', ticketingPlatform: 'Webtickets', priceMinZar: 150, priceMaxZar: 500, format: 'grand-tasting', recurringMonth: 9 },
  { id: 'ev27', name: 'Constantia Fresh', slug: 'constantia-fresh-2026', description: 'Sauvignon Blanc–focused lifestyle festival celebrating the "wild white" grape\'s freshness with food pairings.', startsAt: '2026-09-19', endsAt: '2026-09-20', venueName: 'Buitenverwachting / Groot Constantia', ticketUrl: 'https://grootconstantia.co.za/', ticketingPlatform: 'Direct', priceMinZar: 350, priceMaxZar: 550, format: 'grand-tasting', recurringMonth: 9 },
  // ── OCTOBER ──────────────────────────────────────────────────────────────
  { id: 'ev28', name: 'Pinotage On Tap', slug: 'pinotage-on-tap-2026', description: 'Iconic Pinotage Day festival at Diemersfontein with barrel pours, food, and family entertainment.', startsAt: '2026-10-18', endsAt: '2026-10-18', venueName: 'Diemersfontein Wine & Country Estate, Wellington', ticketUrl: 'https://www.diemersfontein.co.za/events/pinotage-on-tap-2026/', ticketingPlatform: 'iTickets', priceMinZar: 395, priceMaxZar: 1500, format: 'grand-tasting', recurringMonth: 10 },
  { id: 'ev29', name: 'WineX (Standard Bank WineX)', slug: 'winex-2026', description: 'SA\'s longest-running and largest consumer wine expo, run over three evenings in Sandton.', startsAt: '2026-10-30', endsAt: '2026-11-01', venueName: 'Sandton Convention Centre, Johannesburg', ticketUrl: 'https://www.winex.co.za/', ticketingPlatform: 'Direct', priceMinZar: 200, priceMaxZar: 295, format: 'trade-show', recurringMonth: 10 },
  { id: 'ev30', name: 'Sip & Savour @ The River', slug: 'sip-savour-river-2026', description: 'Rebranded riverside open-cellars weekend (formerly Wine on the River) with tastings, live music, and a kids\' zone.', startsAt: '2026-10-25', endsAt: '2026-10-26', venueName: 'Banks of the Breede River, Robertson', ticketUrl: 'https://robertsonwinevalley.com/events/', ticketingPlatform: 'Webtickets', priceMinZar: 250, priceMaxZar: 450, format: 'hop-between', recurringMonth: 10 },
  { id: 'ev31', name: 'Cape Winemakers Guild Auction', slug: 'cwg-auction-2026', description: 'SA\'s premier trade-and-consumer auction of small-lot premium CWG member wines.', startsAt: '2026-10-04', endsAt: '2026-10-04', venueName: 'Virtual live auction', ticketUrl: 'https://www.capewinemakersguild.com/auction/', ticketingPlatform: 'Direct', priceMinZar: 0, priceMaxZar: 0, format: 'trade-show', recurringMonth: 10 },
  // ── NOVEMBER ─────────────────────────────────────────────────────────────
  { id: 'ev32', name: 'Swartland Revolution', slug: 'swartland-revolution-2026', description: 'Iconic artisan Swartland wine movement. Bold reds and old-vine Chenin. Revived after a 10-year hiatus.', startsAt: '2026-11-07', endsAt: '2026-11-07', venueName: 'Riebeek-Kasteel', ticketUrl: 'https://swartlandtourism.co.za/', ticketingPlatform: 'Quicket', priceMinZar: 450, priceMaxZar: 750, format: 'grand-tasting', recurringMonth: 11 },
  { id: 'ev33', name: 'Franschhoek Cap Classique & Champagne Festival', slug: 'cap-classique-sunday-2026', description: 'Franschhoek\'s flagship bubbly festival — MCC + Champagne at the Huguenot Monument. "Cap Classique Sunday".', startsAt: '2026-11-29', endsAt: '2026-11-30', venueName: 'Huguenot Monument, Franschhoek', ticketUrl: 'https://franschhoekcapclassique.co.za/', ticketingPlatform: 'Webtickets', priceMinZar: 450, priceMaxZar: 750, format: 'grand-tasting', recurringMonth: 11 },
  { id: 'ev34', name: 'Greyton Wine Weekend (Summer)', slug: 'greyton-summer-2026', description: 'Summer hop-between village tasting, the warmer-weather sibling of Greyton Fire + Wine.', startsAt: '2026-11-22', endsAt: '2026-11-23', venueName: 'Greyton village (Main Road)', ticketUrl: 'https://www.quicket.co.za/events/356920', ticketingPlatform: 'Quicket', priceMinZar: 640, priceMaxZar: 640, format: 'hop-between', recurringMonth: 11 },
  { id: 'ev35', name: 'Stellenbosch Street Soirée', slug: 'stellenbosch-soiree-2026', description: 'Recurring late-afternoon street tasting (roughly fortnightly Oct–Mar) of 200+ wines from 55+ farms.', startsAt: '2026-11-13', endsAt: '2026-11-13', venueName: 'Drostdy Street, Stellenbosch', ticketUrl: 'https://wineroute.co.za/', ticketingPlatform: 'Plankton', priceMinZar: 250, priceMaxZar: 250, format: 'hop-between', recurringMonth: 11 },
  // ── DECEMBER ─────────────────────────────────────────────────────────────
  { id: 'ev36', name: 'Pick n Pay Wine & Food Festival — Durban', slug: 'pnp-wine-durban-2026', description: 'KZN leg of the PnP wine-and-food tour.', startsAt: '2026-12-05', endsAt: '2026-12-05', venueName: 'Chris Saunders Park, uMhlanga, Durban', ticketUrl: 'https://www.pnpwineandfoodfestival.co.za/', ticketingPlatform: 'Direct', priceMinZar: 350, priceMaxZar: 350, format: 'trade-show', recurringMonth: 12 },
];

export const MOCK_TASTING_HISTORY = [
  { id: 't1', wineName: 'Kanonkop Pinotage', vintage: 2021, stars: 4.5, date: '2026-07-15', notes: 'Rich plum, banana, earth. Paired with braai lamb chops. Will buy again.' },
  { id: 't2', wineName: 'Hamilton Russell Pinot Noir', vintage: 2022, stars: 5, date: '2026-07-12', notes: 'Finessed, forest floor, mushroom. My new benchmark for SA Pinot.' },
  { id: 't3', wineName: 'The Chocolate Block', vintage: 2021, stars: 4, date: '2026-07-08', notes: 'Crowd-pleaser. Smoked meat, white pepper. Great value.' },
  { id: 't4', wineName: 'Graham Beck Brut Rosé', vintage: 0, stars: 4.5, date: '2026-07-04', notes: 'Fine mousse, red berry. Oysters perfection.' },
  { id: 't5', wineName: 'Sadie Skurfberg', vintage: 2021, stars: 5, date: '2026-06-28', notes: 'Extraordinary. Honeyed, mineral, infinite length. Worth every rand.' },
];

export function mockWineById(id: string): MockWine | undefined {
  return MOCK_WINES.find((w) => w.id === id || w.slug === id);
}
export function mockEstateById(id: string): MockEstate | undefined {
  return MOCK_ESTATES.find((e) => e.id === id || e.slug === id);
}
