#!/usr/bin/env python3
"""
geocode-estates.py — Backfill lat/lng for live-DB estates using OSM Nominatim.

The 151 estates in data/wine_estates.json have name + province (Western Cape)
but ZERO coordinates or addresses. This script queries OSM Nominatim for each
estate by name + "wine estate Western Cape South Africa" and writes a SQL
migration (supabase/migrations/0006_estate_geocode.sql) with UPDATE statements.

Usage:
    python3 scripts/geocode-estates.py              # geocode all 0-coord estates
    python3 scripts/geocode-estates.py --limit 10   # test on 10 first
    python3 scripts/geocode-estates.py --dry-run    # show matches without writing

Rate limit: Nominatim policy = 1 request/second. 151 estates ≈ 2.5 min.
We set a descriptive User-Agent per the usage policy.

No API key required. Free. Accuracy depends on OSM coverage of SA wine farms
(major estates like Kanonkop, Klein Constantia are well-mapped; tiny boutique
farms may miss — those stay at 0,0 and the app's haversine filter excludes them).
"""

import json
import time
import sys
import argparse
import urllib.request
import urllib.parse
import os
from typing import Optional, Dict, Any

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ESTATES_JSON = os.path.join(REPO_ROOT, 'data', 'wine_estates.json')
OUTPUT_SQL = os.path.join(REPO_ROOT, 'supabase', 'migrations', '0006_estate_geocode.sql')

USER_AGENT = 'Decanta-Geocoder/1.0 (wine app; contact@decanta.co.za)'
NOMINATIM_URL = 'https://nominatim.openstreetmap.org/search'


def geocode(query: str) -> Optional[Dict[str, Any]]:
    """Query OSM Nominatim, return first result or None."""
    params = urllib.parse.urlencode({
        'q': query,
        'format': 'json',
        'limit': 1,
        'countrycodes': 'za',
    })
    url = f'{NOMINATIM_URL}?{params}'
    req = urllib.request.Request(url, headers={'User-Agent': USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            if data and len(data) > 0:
                return data[0]
    except Exception as e:
        print(f'  ✗ error: {e}', file=sys.stderr)
    return None


def main():
    parser = argparse.ArgumentParser(description='Geocode Decanta estates via OSM Nominatim')
    parser.add_argument('--limit', type=int, default=None, help='Only geocode N estates')
    parser.add_argument('--dry-run', action='store_true', help='Print matches, don\'t write SQL')
    args = parser.parse_args()

    with open(ESTATES_JSON) as f:
        estates = json.load(f)

    # Only geocode estates with missing coordinates
    todo = [e for e in estates if not e.get('latitude') or not e.get('longitude')]
    print(f'Total estates: {len(estates)}')
    print(f'Missing coords: {len(todo)}')
    if args.limit:
        todo = todo[:args.limit]
        print(f'Limited to: {len(todo)}')

    results = []
    found = 0
    for i, estate in enumerate(todo):
        name = estate.get('name', '').strip()
        if not name:
            continue
        # Try progressively broader queries
        queries = [
            f'{name} wine estate Western Cape South Africa',
            f'{name} Western Cape South Africa',
            f'{name} South Africa winery',
        ]
        result = None
        query_used = ''
        for q in queries:
            result = geocode(q)
            if result:
                query_used = q
                break
            time.sleep(1.1)  # Nominatim rate limit

        if result:
            lat = float(result['lat'])
            lon = float(result['lon'])
            results.append({
                'id': estate['id'],
                'name': name,
                'lat': lat,
                'lon': lon,
                'query': query_used,
                'osm_type': result.get('type', ''),
                'display_name': result.get('display_name', '')[:100],
            })
            found += 1
            status = f'✓ {name} → {lat:.4f}, {lon:.4f}'
            if args.dry_run:
                status += f'  [{result.get("display_name", "")[:60]}]'
            print(f'[{i+1}/{len(todo)}] {status}')
        else:
            print(f'[{i+1}/{len(todo)}] ✗ {name} — not found')

        time.sleep(1.1)  # Nominatim rate limit

    print(f'\n=== Results: {found}/{len(todo)} geocoded ===')

    if args.dry_run:
        print('(dry-run — no SQL written)')
        return

    if not results:
        print('Nothing to write.')
        return

    # Write SQL migration
    os.makedirs(os.path.dirname(OUTPUT_SQL), exist_ok=True)
    with open(OUTPUT_SQL, 'w') as f:
        f.write('-- Auto-generated by scripts/geocode-estates.py\n')
        f.write('-- Backfills latitude/longitude for estates via OSM Nominatim.\n')
        f.write(f'-- {found}/{len(todo)} estates geocoded.\n\n')
        for r in results:
            f.write(
                f"UPDATE estates SET latitude = {r['lat']}, longitude = {r['lon']} "
                f"WHERE id = '{r['id']}';\n"
            )
        f.write(f'\n-- Verification: count of estates with coordinates\n')
        f.write(f"SELECT count(*) FROM estates WHERE latitude IS NOT NULL;\n")

    print(f'SQL migration written: {OUTPUT_SQL}')
    print(f'Run with: supabase db push  (or paste into SQL Editor)')


if __name__ == '__main__':
    main()
